### ISSUE TITLE
Exception : Mediapipe dependencies not found

### ISSUE THREAD

**Issue by ekanpycoderx** [samborba/training-mediapipe-model#4]
```shell
Traceback (most recent call last):
  File "src/preprocess.py", line 98, in <module>
    main(input_data_path, classification)
  File "src/preprocess.py", line 35, in main
    raise Exception("Mediapipe dependencies not found.")
Exception: Mediapipe dependencies not found.
```

**Comment by ekanpycoderx** [comment]
I dunno know which dependencies it is talking about 
here's how i did it 
```shell
python src/preprocess.py --input_dataset_path C:\Users\ekans\Desktop\mediapipe\Model --classification User1
```
